services:
    traefik:
        container_name: lara-traefik
        image: "${TRAEFIK_VERSION}"
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        ports:
            - "${TRAEFIK_HTTP_PORT}"
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

    # NGINX Service
    nginx:
        container_name: lara-nginx
        build:
            context: "${DOCKER_CONTEXT}"
            dockerfile: development/nginx/Dockerfile
            args:
                - ARG_NGINX_VERSION=${NGINX_VERSION}
                - ARG_APP_DIR=${APP_DIR}
        volumes:
            - "${APP_VOLUMES_HOST}:${APP_VOLUMES_CONTAINER}"
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT_HOST}:${NGINX_PORT_CONTAINER}"
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.lara.rule=Host(`lara.localhost`)
            - traefik.http.routers.lara.entryPoints=http
            - traefik.http.services.lara.loadBalancer.server.port=80

    lara-php-fpm:
        container_name: lara-php-fpm
        build:
            context: "${DOCKER_CONTEXT}"
            dockerfile: development/php-fpm/Dockerfile
            args:
                - ARG_PHP_FPM_VERSION=${PHP_FPM_VERSION}
                - ARG_XDEBUG_VERSION=${XDEBUG_VERSION}
                - ARG_PHP_INI_DIR=${PHP_INI_DIR}
                - ARG_APP_DIR=${APP_DIR}
        environment:
            APP_ENV: "${APP_ENV}"
            APP_DEBUG: "${APP_DEBUG}"
            PHP_IDE_CONFIG: serverName="${SERVER_NAME}"
            DB_HOST: "${DB_HOST}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
            DB_NAME: "${DB_NAME}"

            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD_FILE: /run/secrets/lara_mailer_password
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN_FILE: /run/secrets/sentry_dsn
            JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - "${APP_VOLUMES_HOST}:${APP_VOLUMES_CONTAINER}"
        restart: unless-stopped
        secrets:
            - lara_mailer_password
            - sentry_dsn
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key

    lara-php-cli:
        container_name: lara-php-cli
        build:
            context: "${DOCKER_CONTEXT}"
            dockerfile: development/php-cli/Dockerfile
            args:
                - ARG_PHP_CLI_VERSION=${PHP_CLI_VERSION}
                - ARG_PHP_USER=${PHP_USER}
                - ARG_XDEBUG_VERSION=${XDEBUG_VERSION}
                - ARG_PHP_INI_DIR=${PHP_INI_DIR}
                - ARG_APP_DIR=${APP_DIR}
                - ARG_COMPOSER_ALLOW_SUPERUSER=${COMPOSER_ALLOW_SUPERUSER}
        restart: unless-stopped
        tty: true
        environment:
            APP_ENV: "$APP_ENV{}"
            APP_DEBUG: "${APP_DEBUG}"
            DB_CONNECTION: "${DB_CONNECTION}"
            DB_HOST: "${DB_HOST}"
            DB_PORT: "${DB_PORT_CONTAINER}"
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"

            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD_FILE: /run/secrets/lara_mailer_password
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN_FILE: /run/secrets/sentry_dsn
            JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - "${APP_VOLUMES_HOST}:${APP_VOLUMES_CONTAINER}"
        secrets:
#            - lara_db_password
            - lara_mailer_password
            - sentry_dsn
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key

    pg:
        container_name: lara-postgres
        image: postgres:13.3-alpine
        environment:
            POSTGRES_DB: "${DB_NAME}"
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - lara-postgres:/var/lib/postgresql/data
        restart: always
        ports:
            - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"

    lara-adminer:
        container_name: lara-adminer
        image: $ADMINER_VERSION
        restart: always
        ports:
            - "${ADMINER_PORT_HOST}:${ADMINER_PORT_CONTAINER}"

secrets:
    lara_db_password:
        file: ./docker/development/secrets/lara_db_password
    lara_mailer_password:
        file: ./docker/development/secrets/lara_mailer_password
    sentry_dsn:
        file: ./docker/development/secrets/sentry_dsn
    jwt_encryption_key:
        file: ./docker/development/secrets/jwt_encryption_key
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public_key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private_key
    backup_aws_secret_access_key:
        file: ./docker/development/secrets/backup_aws_secret_access_key

volumes:
    lara-postgres:

networks:
    traefik-public:
        name: traefik-public
